global_planner:
  # Params
  useGlobalMap: true
  inflationGridSize: 6
  maxProcessTime: 2000 # milisecond

  # Publish
  gridMapTopic: "/gridmap" 
  globalPathTopic: "/global_path"



local_planner:
  test: "done"