global_planner:
  # Params
  useGlobalMap: true
  inflationGridSize: 3
  

  # Subscribe
  gridMapTopic: "/gridmap" 
  localmapTopic: "/traversability/map2"
  globalPathTopic: "/global_path"
  # Publish



local_planner:
  test: "done"