global_planner:
  # Params
  useGlobalMap: true
  getGlobalMapFromTopic: true
  inflationGridSize: 1
  maxProcessTime: 2000 # milisecond

  # Publish
  gridMapTopic: "/gridmap" 
  globalPathTopic: "/global_path"
  localPathTopic: "/local_path"
  # localMapTopic: "/gridmap"



local_planner:
  test: "done"