global_planner:
  # Params
  useGlobalmap: true
  inflationGridSize: 5
  

  # Subscribe
  gridMapTopic: "/gridmap" 
  localmapTopic: "/traversability/map2"
  globalPathTopic: "/global_path"
  # Publish



local_planner:
  test: "done"