global_planner:
  # Params
  useGlobalMap: true
  getGlobalMapFromTopic: true
  robotRadius: 0.6
  maxProcessTime: 2000 # milisecond

  # Publish
  gridMapTopic: "/gridmap" 
  globalPathTopic: "/global_path"
  localPathTopic: "/local_path"
  # localMapTopic: "/elevation_map_raw_visualization/elevation_cloud"
  # localMapTopic: "/laser_cloud"



local_planner:
  test: "done"