global_planner:

  usePrebuiltMap: true
  
  #######################
  sensorFrameId: "velodyne_tilted"

  # Subscribe
  # occupancy map: given by service
  laserScanTopic: "/tim581_front/sca"
  localmapTopic: "/traversability/map2"

  # Publish
  globalMapTopic: "/gridmap"
  globaSubmapTopic: "/gridmap_sub"
  dijkstraPathTopic: "/path_raw2"
  ebandPathTopic: "/path_banded"
  ebandBubbleTopic: "/elastic_band"

  # Params
  inflationGridSize: 5
  useGlobalmap: false

local_planner:
  test: "done"